<Project>

	<Import Project="version.props" />

	<PropertyGroup>
		<Authors>Stephen Denne</Authors>
		<Copyright>Copyright © Stephen Denne 2024, 2025</Copyright>
		<Company>Datacute</Company>
		<PackageProjectUrl>https://github.com/datacute/EmbeddedResourcePropertyGenerator</PackageProjectUrl>
		<CheckEolTargetFramework>false</CheckEolTargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<NoPackageAnalysis>true</NoPackageAnalysis>
		<PackageOutputPath>$(MSBuildThisFileDirectory)\artifacts</PackageOutputPath>
	</PropertyGroup>

	<Import Project="releasenotes.props" />

</Project>