using System.Text;
using Microsoft.CodeAnalysis;

namespace Datacute.EmbeddedResourcePropertyGenerator
{
    public readonly struct CodeGenerator
    {
        public CodeGenerator(in AttributeContext context,
            string resourceSearchPath,
            in ImmutableEquatableArray<EmbeddedResource> embeddedResources,
            in GeneratorOptions options,
            in CancellationToken cancellationToken)
        {
            _context = context;
            _resourceSearchPath = resourceSearchPath;
            _embeddedResources = embeddedResources;
            _options = options;
            _cancellationToken = cancellationToken;
            _buffer = new StringBuilder();
            _propertyNames = new Dictionary<string, EmbeddedResource>();
        }

        private static readonly Dictionary<int, string> IndentationCache = new();
        private const char IndentationCharacter = ' ';
        private const int IndentationCharacterRepetition = 4;

        private readonly AttributeContext _context;
        private readonly string _resourceSearchPath;
        private readonly ImmutableEquatableArray<EmbeddedResource> _embeddedResources;
        private readonly GeneratorOptions _options;
        private readonly StringBuilder _buffer;
        private readonly CancellationToken _cancellationToken;
        
        private readonly Dictionary<string, EmbeddedResource> _propertyNames;

        public string GenerateSource()
        {
            _cancellationToken.ThrowIfCancellationRequested();
            GeneratePropertyNames();

            _buffer.Clear();
            AutoGeneratedComment();
            var indent = StartNamespace();
            indent = ParentClasses(indent);
            indent = ClassDocComments(indent);
            indent = PartialTypeDeclaration(indent);
            indent = AppendStartBlock(indent);
            indent = AppendStartEmbeddedResourceClass(indent);
            indent = ReadMethod(indent);
            indent = BackingFields(indent);
            indent = ResourceNames(indent);
            indent = AppendEndBlock(indent);
            indent = AppendPartialMethods(indent);
            indent = ProcessMatchingEmbeddedResources(indent);
            indent = AppendEndBlock(indent);
            indent = EndParentClasses(indent);
            if (indent > 0) // The choice to use file scoped namespaces is made within StartNamespace()
            {
                AppendEndBlock(indent);
            }

            AppendDiagnosticLogs();
            return _buffer.ToString();
        }

        private void GeneratePropertyNames()
        {
            _propertyNames.Clear();
            foreach (var text in _embeddedResources)
            {
                _cancellationToken.ThrowIfCancellationRequested();
                var resourceFilePath = text.Path;

                var propertyName = resourceFilePath.GetPropertyName(_context.Name);
                RecordPropertyNameForResource(propertyName, text);
            }
        }

        private void RecordPropertyNameForResource(string propertyName, EmbeddedResource text)
        {
            // finding "Classname.txt" (converted to "Classname_txt")
            // before an actual "Classname_txt.txt"
            // should result in "Classname.txt" being adjusted further
            if (_propertyNames.TryGetValue(propertyName, out var existingText))
            {
                if (existingText.Path.Length >= text.Path.Length)
                {
                    RecordPropertyNameForResource(propertyName + "_", text);
                }
                else
                {
                    _propertyNames[propertyName] = text;
                    RecordPropertyNameForResource(propertyName + "_", existingText);
                }
            }
            else
            {
                _propertyNames.Add(propertyName, text);
            }
        }

        private void AutoGeneratedComment() => _buffer.AppendLine(Templates.AutoGeneratedComment);

        /// <returns>The indentation level</returns>
        private int StartNamespace()
        {
            if (_context.ContainingNamespaceIsGlobalNamespace) return 0;

            _buffer.Append("namespace ");
            _buffer.Append(_context.ContainingNamespaceDisplayString);
            // Here is where we could chose whether to use file scoped namespaces or not
            // depending on whether C# language in use is >= 10
            _buffer.Append(';').AppendLine();
            return 0; // No indentation needed for file scoped namespace
        }

        private int ParentClasses(int indent)
        {
            if (_context.HasParentClasses)
            {
                indent = StartParentClasses(indent);
            }
            return indent;
        }

        private int StartParentClasses(int indent)
        {
            foreach (var parentClass in _context.ParentClasses)
            {
                AppendIndent(indent);
                var accessibilityModifier = GetAccessibility(parentClass.Accessibility);
                var staticModifier = GetStaticModifier(parentClass.IsStatic);
                var genericTypes = GetGenericTypes(parentClass.TypeParameters);
                _buffer.AppendLine($"{accessibilityModifier}{staticModifier}partial {parentClass.RecordStructOrClass} {parentClass.Name}{genericTypes}");
                AppendStartBlock(indent);
                indent++;
            }
            return indent;
        }

        private int ReadMethod(int indent)
        {
            if (_options.IsDesignTimeBuild) return indent;

            var indentString = StringForIndent(indent);
            _buffer.AppendFormat(Templates.ReadMethod, indentString, StringForIndent(1), _context.Name);
            return indent;
        }

        private int BackingFields(int indent)
        {
            if (_options.IsDesignTimeBuild) return indent;

            AppendIndent(indent);
            _buffer.AppendLine(Templates.BackingFieldClass);
            indent = AppendStartBlock(indent);

            var innerIndentString = StringForIndent(indent);
            foreach (var propertyName in _propertyNames.Keys)
            {
                _cancellationToken.ThrowIfCancellationRequested();
                _buffer.AppendFormat(Templates.BackingField, innerIndentString, propertyName).AppendLine();
            }

            indent = AppendEndBlock(indent);
            return indent;
        }

        private int ResourceNames(int indent)
        {
            if (_options.IsDesignTimeBuild) return indent;

            AppendIndent(indent);
            _buffer.AppendLine(Templates.ResourceNameClass);
            indent = AppendStartBlock(indent);

            var innerIndentString = StringForIndent(indent);
            foreach (var kvp in _propertyNames)
            {
                _cancellationToken.ThrowIfCancellationRequested();

                var propertyName = kvp.Key;
                var text = kvp.Value;
                var resourceFilePath = text.Path;

                var embeddedResourceName = resourceFilePath.GetEmbeddedResourceName(
                    _options.ProjectDir,
                    _options.RootNamespace);

                _buffer.AppendFormat(Templates.ResourceName, innerIndentString, propertyName, embeddedResourceName);
            }
            indent = AppendEndBlock(indent);
            return indent;
        }

        private int ClassDocComments(int indent)
        {
            if (_options.IsDesignTimeBuild) return indent;

            var indentString = StringForIndent(indent);

            var path = _resourceSearchPath.Substring(_options.ProjectDir.Length)
                .Replace(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            _buffer.AppendFormat(Templates.ClassDocComments, indentString, path, _context.ExtensionArg);

            return indent;
        }

        private int PartialTypeDeclaration(int indent)
        {
            _buffer.AppendFormat(
                "{0}{1}{2}partial {3} {4}{5}",
                StringForIndent(indent),
                GetAccessibility(),
                GetStatic(),
                _context.RecordStructOrClass,
                _context.Name,
                GetGenericTypes()
            ).AppendLine();

            return indent;
        }

        private string GetAccessibility() => GetAccessibility(_context.DeclaredAccessibility);

        private static string GetAccessibility(Accessibility accessibility)
        {
            return accessibility switch
            {
                Accessibility.Private => "private ",
                Accessibility.ProtectedAndInternal => "private protected ",
                Accessibility.Protected => "protected ",
                Accessibility.Internal => "internal ",
                Accessibility.ProtectedOrInternal => "protected internal ",
                Accessibility.Public => "public ",
                _ => throw new ArgumentOutOfRangeException(nameof(accessibility), accessibility, null)
            };
        }

        private string GetStatic() => GetStaticModifier(_context.IsStatic);

        private string GetStaticModifier(bool isStatic) => isStatic ? "static " : "";

        private string GetGenericTypes() => GetGenericTypes(_context.TypeParameters);

        private string GetGenericTypes(string[] genericTypes) =>
            genericTypes.Any()
                ? $"<{string.Join(",", genericTypes)}>"
                : string.Empty;

        private int AppendStartBlock(int indent)
        {
            AppendIndent(indent);
            _buffer.AppendLine("{");
            return indent + 1;
        }

        private int AppendStartEmbeddedResourceClass(int indent)
        {
            AppendIndent(indent);
            _buffer.AppendLine(Templates.StartEmbeddedResourceClass);
            indent = AppendStartBlock(indent);
            return indent;
        }

        private int AppendPartialMethods(int indent)
        {
            AppendIndent(indent);
            _buffer.AppendLine(Templates.PartialReadMethods);
            AppendIndent(indent);
            _buffer.AppendLine(Templates.PartialAlterMethods);
            return indent;
        }

        private int ProcessMatchingEmbeddedResources(int indent)
        {
            var indentString = StringForIndent(indent);
            foreach (var kvp in _propertyNames)
            {
                _cancellationToken.ThrowIfCancellationRequested();

                var propertyName = kvp.Key;
                var text = kvp.Value;
                var resourceFilePath = text.Path;

                if (_options.IsDesignTimeBuild)
                {
                    AppendIndent(indent);
                    _buffer.AppendFormat(Templates.DesignTimePropertyTemplate, propertyName).AppendLine();
                }
                else
                {
                    var resourceFileName = resourceFilePath.GetFileName();
                    var docCommentCode = text.DocCommentCode;
                    if (docCommentCode is null)
                    {
                        continue;
                    }

                    var indentedDocCommentCodeSb = new StringBuilder();
                    foreach (var docCommentLine in docCommentCode.Split(new[] { '\r', '\n' },
                                 StringSplitOptions.RemoveEmptyEntries))
                    {
                        indentedDocCommentCodeSb.AppendLine();
                        indentedDocCommentCodeSb.Append(indentString);
                        indentedDocCommentCodeSb.Append(docCommentLine);
                    }

                    _buffer.AppendFormat(Templates.PropertyTemplate,
                        indentString,
                        StringForIndent(1),
                        propertyName,
                        resourceFileName,
                        indentedDocCommentCodeSb);
                }
            }

            return indent;
        }

        private int AppendEndBlock(int indent)
        {
            indent--;
            AppendIndent(indent);
            _buffer.AppendLine("}");
            return indent;
        }

        private int EndParentClasses(int indent)
        {
            // Close parent classes if any
            if (_context.HasParentClasses)
            {
                for (int i = 0; i < _context.ParentClasses.Length; i++)
                {
                    indent = AppendEndBlock(indent);
                }
            }

            return indent;
        }

        private void AppendDiagnosticLogs()
        {
            if (_context.OutputDiagnosticTraceLog)
            {
                _buffer.AppendLine();
                _buffer.AppendLine("/* Diagnostic Trace Log");
                LightweightTrace.Add(TrackingNames.DiagnosticTraceLog_Written);
                LightweightTrace.GetTrace(_buffer, TrackingNames.TracingNames);
                _buffer.AppendLine("*/");
            }
        }

        private string StringForIndent(int indent)
        {
            if (!IndentationCache.TryGetValue(indent, out var indentString))
            {
                indentString = new string(IndentationCharacter, indent * IndentationCharacterRepetition);
                IndentationCache[indent] = indentString;
            }
            return indentString;
        }

        private void AppendIndent(int indent)
        {
            var indentString = StringForIndent(indent);
            _buffer.Append(indentString);
        }
    }
}