using Datacute.IncrementalGeneratorExtensions;

namespace Datacute.EmbeddedResourcePropertyGenerator
{
    public class CodeGenerator : SourceTextGeneratorBase<AttributeData>
    {
        public CodeGenerator(in AttributeContextAndData<AttributeData> contextAndData,
            string resourceSearchPath,
            in EquatableImmutableArray<EmbeddedResource> embeddedResources,
            in GeneratorOptions options,
            in CancellationToken cancellationToken) 
            : base(contextAndData, cancellationToken) 
        {
            _contextData = contextAndData.AttributeData;
            _resourceSearchPath = resourceSearchPath;
            _embeddedResources = embeddedResources;
            _options = options;
            _propertyNames = new Dictionary<string, EmbeddedResource>();
        }

        private readonly AttributeData _contextData;
        private readonly string _resourceSearchPath;
        private readonly EquatableImmutableArray<EmbeddedResource> _embeddedResources;
        private readonly GeneratorOptions _options;
        
        private readonly Dictionary<string, EmbeddedResource> _propertyNames;

        protected override void PrepareForGeneration()
        {
            Token.ThrowIfCancellationRequested(102);
            Buffer.Clear();

            GeneratePropertyNames();
        }

        private void GeneratePropertyNames()
        {
            _propertyNames.Clear();
            foreach (var text in _embeddedResources)
            {
                Token.ThrowIfCancellationRequested(103);
                var resourceFilePath = text.Path;

                var propertyName = resourceFilePath.GetPropertyName(Context.Name);
                RecordPropertyNameForResource(propertyName, text);
            }
        }

        private void RecordPropertyNameForResource(string propertyName, EmbeddedResource text)
        {
            // finding "Classname.txt" (converted to "Classname_txt")
            // before an actual "Classname_txt.txt"
            // should result in "Classname.txt" being adjusted further
            if (_propertyNames.TryGetValue(propertyName, out var existingText))
            {
                if (existingText.Path.Length >= text.Path.Length)
                {
                    RecordPropertyNameForResource(propertyName + "_", text);
                }
                else
                {
                    _propertyNames[propertyName] = text;
                    RecordPropertyNameForResource(propertyName + "_", existingText);
                }
            }
            else
            {
                _propertyNames.Add(propertyName, text);
            }
        }

        protected override string AutoGeneratedComment => Templates.AutoGeneratedComment;

        protected override void AppendDocComments()
        {
            if (_options.IsDesignTimeBuild) return;

            var path = _resourceSearchPath.Substring(_options.ProjectDir.Length)
                .Replace(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            Buffer.AppendFormatLines(Templates.ClassDocComments, path, _contextData.ExtensionArg);
        }

        protected override void AppendCustomMembers()
        {
            AppendStartEmbeddedResourceClass();
            AppendStartBlock();
            AppendReadMethod();
            AppendBackingFields();
            AppendResourceNames();
            AppendEndBlock();
            AppendPartialMethods();
            AppendMatchingEmbeddedResources();
        }

        private void AppendStartEmbeddedResourceClass()
        {
            Buffer.AppendLine(Templates.StartEmbeddedResourceClass);
        }

        private void AppendReadMethod()
        {
            if (_options.IsDesignTimeBuild) return;

            Buffer.AppendFormatLines(Templates.ReadMethod, Buffer.SingleIndent, Context.Name);
        }

        private void AppendBackingFields()
        {
            if (_options.IsDesignTimeBuild) return;

            Buffer.AppendLine(Templates.BackingFieldClass);
            AppendStartBlock();

            foreach (var kvp in _propertyNames.OrderBy(kvp => kvp.Value.Path))
            {
                Token.ThrowIfCancellationRequested(104);
                var propertyName = kvp.Key;
                Buffer.AppendLine(string.Format(Templates.BackingField, propertyName));
            }

            AppendEndBlock();
        }

        private void AppendResourceNames()
        {
            if (_options.IsDesignTimeBuild) return;

            Buffer.AppendLine(Templates.ResourceNameClass);
            AppendStartBlock();

            foreach (var kvp in _propertyNames.OrderBy(kvp => kvp.Value.Path))
            {
                Token.ThrowIfCancellationRequested(105);

                var propertyName = kvp.Key;
                var text = kvp.Value;
                var resourceFilePath = text.Path;

                var embeddedResourceName = resourceFilePath.GetEmbeddedResourceName(
                    _options.ProjectDir,
                    _options.RootNamespace);

                Buffer.AppendLine(string.Format(Templates.ResourceName, propertyName, embeddedResourceName));
            }
            AppendEndBlock();
        }

        private void AppendPartialMethods()
        {
            Buffer.AppendLine(Templates.PartialReadMethods);
            Buffer.AppendLine(Templates.PartialAlterMethods);
        }

        private void AppendMatchingEmbeddedResources()
        {
            foreach (var kvp in _propertyNames.OrderBy(kvp => kvp.Value.Path))
            {
                Token.ThrowIfCancellationRequested(106);

                var propertyName = kvp.Key;
                var text = kvp.Value;

                if (_options.IsDesignTimeBuild)
                {
                    Buffer.AppendLine(string.Format(Templates.DesignTimePropertyTemplate, propertyName));
                }
                else
                {
                    var docCommentCode = text.DocCommentCode;
                    if (docCommentCode is null)
                    {
                        continue;
                    }

                    var resourceFileName = text.Path.GetFileName();
                    Buffer.AppendFormatLines(Templates.PropertyTemplate,
                        Buffer.SingleIndent,
                        propertyName,
                        resourceFileName,
                        docCommentCode);
                }
            }
        }

        protected override void AppendDiagnosticLogs()
        {
            if (_contextData.OutputDiagnosticTraceLog)
            {
                Buffer.AppendLine();
                Buffer.Direct.AppendDiagnosticsComment(TrackingNameDescriptions.EventNameMap);
                LightweightTrace.Add(TrackingNames.DiagnosticTraceLogWritten);
            }
        }
    }
}