<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>10</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IncludeBuildOutput>false</IncludeBuildOutput> <!-- Do not include the generator as a lib dependency in consuming projects -->
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <AssemblyName>Datacute.EmbeddedResourcePropertyGenerator</AssemblyName>
        <RootNamespace>Datacute.EmbeddedResourcePropertyGenerator</RootNamespace>
        <NoWarn>NU5128</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <DevelopmentDependency>true</DevelopmentDependency>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>Datacute.EmbeddedResourcePropertyGenerator</PackageId>
        <Title>Datacute Embedded Resource Property Generator</Title>
        <Description>A source generator creating properties for embedded resources in a project.</Description>
        <PackageTags>SourceGenerator</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <PropertyGroup>
        <Datacute_IncludeReadmeFile>true</Datacute_IncludeReadmeFile>
        <DefineConstants>$(DefineConstants);DATACUTE_EXCLUDE_TABINDENTINGLINEAPPENDER</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Datacute.AdditionalTextConstantGenerator" Version="1.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Datacute.IncrementalGeneratorExtensions" Version="1.0.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.4.0" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <!-- Pack the generator dll in the analyzers/dotnet/cs path -->
        <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />

        <None Include="./Datacute.EmbeddedResourcePropertyGenerator.props" Pack="true" PackagePath="build" Visible="true" />

        <None Include="../README.md" Pack="true" PackagePath="" Visible="false" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Templates/EmbeddedResourcePropertiesAttribute.cs" />
        <AdditionalFiles Include="Templates/EmbeddedResourcePropertiesAttribute.cs" />
    </ItemGroup>
</Project>
