// Polyfill for netstandard2.0: required for init-only setters (generated by readonly record struct)
// ReSharper disable once CheckNamespace
namespace System.Runtime.CompilerServices
{
    // ReSharper disable once UnusedType.Global
    internal static class IsExternalInit { }
}
