//HintName: OuterClass_T.InnerClass.EmbeddedResourceProperties.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Datacute.EmbeddedResourcePropertyGenerator.
//     Version: 1.2.3
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

public static partial class OuterClass<T>
{
    /// <summary>
    /// This class's properties are generated from project files meeting the criteria:
    /// <list type="bullet">
    /// <item>
    /// <description>they are an <c>EmbeddedResource</c></description>
    /// </item>
    /// <item>
    /// <description>they are in the project folder <c>InnerClass</c></description>
    /// </item>
    /// <item>
    /// <description>they have the extension <c>.txt</c></description>
    /// </item>
    /// <item>
    /// <description>Number of matching resources: 1</description>
    /// </item>
    /// </list>
    /// </summary>
    public static partial class InnerClass
    {
        private static class EmbeddedResource
        {
            public static string Read(string resourceName)
            {
                var assembly = typeof(InnerClass).Assembly;
                using var stream = assembly.GetManifestResourceStream(resourceName)!;
                using var streamReader = new global::System.IO.StreamReader(stream, global::System.Text.Encoding.UTF8);
                var resourceText = streamReader.ReadToEnd();
                return resourceText;
            }
            public static class ResourceName
            {
                public const string Example = "EmbeddedResourcePropertyGenerator.Tests.InnerClass.example.txt";
            }
        }
        static partial void ReadEmbeddedResourceValue(ref string? backingField, string resourceName, string propertyName);
        static partial void AlterEmbeddedResourceReturnValue(ref string value, string resourceName, string propertyName);

        /// <summary>Text value of the Embedded Resource: example.txt</summary>
        /// <value>
        /// <code>
        /// Example text content
        /// </code>
        /// </value>
        /// <remarks>
        /// The value is read from the embedded resource on first access.
        /// </remarks>
        public static string Example
        {
            get
            {
                ReadEmbeddedResourceValue(ref field, EmbeddedResource.ResourceName.Example, "Example");
                var value = field ??= EmbeddedResource.Read(EmbeddedResource.ResourceName.Example);
                AlterEmbeddedResourceReturnValue(ref value, EmbeddedResource.ResourceName.Example, "Example");
                return value;
            }
        }
    }
}
