using Datacute.EmbeddedResourcePropertyGenerator;
using Datacute.IncrementalGeneratorExtensions;
using Microsoft.CodeAnalysis;
using Shouldly;

namespace EmbeddedResourcePropertyGenerator.Tests;

public class GeneratorTests
{
    private const string InputSource = /* language=c# */
        $$"""
          using Datacute.EmbeddedResourcePropertyGenerator;
          namespace {{TestHelper.TestNamespace}};
          [EmbeddedResourceProperties(".txt", "Queries")]
          public static partial class Queries;
          """;

    // Create a list to hold all additional texts
    private readonly List<AdditionalText> _additionalTexts =
    [
        new InMemoryAdditionalText(
            TestHelper.TestPath("Queries/example.txt"),
            """
            Example text content (Line 1)
            Example text content (Line 2)
            Example text content (Line 3)
            Example text content (Line 4)
            Example text content (Line 5)
            Example text content (Line 6)
            Example text content (Line 7)
            Example text content (Line 8)
            Example text content (Line 9)
            Example text content (Line 10)
            Example text content (Line 11)
            Example text content (Line 12)
            """),

        new InMemoryAdditionalText(
            TestHelper.TestPath("Queries/example2.file"),
            "Example text content with the wrong extension - should not be included"),

        new InMemoryAdditionalText(
            TestHelper.TestPath("WrongFolder/example3.txt"),
            "Example text content in the wrong folder - should not be included")
    ];

    private const string ExpectedOutput1 = /* language=c# */
            $$"""
              //------------------------------------------------------------------------------
              // <auto-generated>
              //     This code was generated by the Datacute.EmbeddedResourcePropertyGenerator.
              // </auto-generated>
              //------------------------------------------------------------------------------

              #nullable enable

              namespace {{TestHelper.TestNamespace}};
              
              /// <summary>
              /// This class's properties are generated from project files meeting the criteria:
              /// <list type="bullet">
              /// <item>
              /// <description>they are both an <c>EmbeddedResource</c> and an <c>AdditionalFile</c></description>
              /// </item>
              /// <item>
              /// <description>they are in the project folder <c>Queries</c></description>
              /// </item>
              /// <item>
              /// <description>they have the extension <c>.txt</c></description>
              /// </item>
              /// </list>
              /// </summary>
              public static partial class Queries
              {
                  private static class EmbeddedResource
                  {
                      public static string Read(string resourceName)
                      {
                          var assembly = typeof(Queries).Assembly;
                          using var stream = assembly.GetManifestResourceStream(resourceName)!;
                          using var streamReader = new global::System.IO.StreamReader(stream, global::System.Text.Encoding.UTF8);
                          var resourceText = streamReader.ReadToEnd();
                          return resourceText;
                      }
                      public static class BackingField
                      {
                          public static string? Example;
                      }
                      public static class ResourceName
                      {
                          public const string Example = "{{TestHelper.TestNamespace}}.Queries.example.txt";
                      }
                  }
                  static partial void ReadEmbeddedResourceValue(ref string? backingField, string resourceName, string propertyName);
                  static partial void AlterEmbeddedResourceReturnValue(ref string value, string resourceName, string propertyName);
              
                  /// <summary>Text value of the Embedded Resource: example.txt</summary>
                  /// <value>
                  /// <code>
                  /// Example text content (Line 1)
                  /// Example text content (Line 2)
                  /// Example text content (Line 3)
                  /// Example text content (Line 4)
                  /// Example text content (Line 5)
                  /// Example text content (Line 6)
                  /// Example text content (Line 7)
                  /// Example text content (Line 8)
                  /// Example text content (Line 9)
                  /// Example text content (Line 10)
                  /// ... 2 more lines
                  /// </code>
                  /// </value>
                  /// <remarks>
                  /// The value is read from the embedded resource on first access.
                  /// </remarks>
                  public static string Example
                  {
                      get
                      {
                          ReadEmbeddedResourceValue(ref EmbeddedResource.BackingField.Example, EmbeddedResource.ResourceName.Example, "Example");
                          var value = EmbeddedResource.BackingField.Example ??= EmbeddedResource.Read(EmbeddedResource.ResourceName.Example);
                          AlterEmbeddedResourceReturnValue(ref value, EmbeddedResource.ResourceName.Example, "Example");
                          return value;
                      }
                  }
              }

              """;

    [Fact]
    public void CanGenerate()
    {
        // run the generator, passing in the inputs and the tracking names
        var (diagnostics, output1, output2)
            = TestHelper.GetGeneratedOutput<Generator>(
                TestHelper.NoModification,
                _additionalTexts,
                TestHelper.GetTrackingNames<TrackingNames>(),
                TestHelper.NoModification,
                InputSource);

        // Assert the output
        diagnostics.ShouldBeEmpty();
        output1.LastOrDefault().ShouldBe(ExpectedOutput1);
        output2.LastOrDefault().ShouldBe(ExpectedOutput1);
    }

    [Fact]
    public void ChangesToUnreferencedAdditionText_PipelineEntirelyCached()
    {
        // run the generator, passing in the inputs and the tracking names
        var (diagnostics, output1, output2)
            = TestHelper.GetGeneratedOutput<Generator>(
                TestHelper.NoModification,
                _additionalTexts,
                TestHelper.GetTrackingNames<TrackingNames>(),
                (driver, compilation) =>
                {
                    // The second additional text (with index 1) is not matched by the attribute
                    if (_additionalTexts[1] is InMemoryAdditionalText changingText)
                    {
                        var newText = changingText.Replace(changingText.TextSpan, "Changed content");
                        driver = driver.ReplaceAdditionalText(changingText, newText);
                    }

                    return (driver, compilation);
                },
                InputSource);

        // Assert the output
        diagnostics.ShouldBeEmpty();
        output1.LastOrDefault().ShouldBe(ExpectedOutput1);
        output2.LastOrDefault().ShouldBe(ExpectedOutput1);
    }

    [Fact]
    public void ModifiedText_ProducesMinimalUpdates()
    {
        // run the generator, passing in the inputs and the tracking names
        var (diagnostics, output1, output2)
            = TestHelper.GetGeneratedOutput<Generator>(
                TestHelper.NoModification,
                _additionalTexts,
                [
                    nameof(GeneratorStage.ForAttributeWithMetadataName),
                    nameof(TrackingNames.AnalyzerConfigOptions),
                    nameof(TrackingNames.AttributesAndOptionsCombined),
                    nameof(TrackingNames.AttributeGlobInfoSelected),
                    nameof(TrackingNames.AttributeGlobsSelected)
                ],
                (driver, compilation) =>
                {
                    if (_additionalTexts[0] is InMemoryAdditionalText changingText)
                    {
                        // Not only does the DocComment change,
                        // but the truncation no longer happens.
                        // Truncation happens after 10 lines
                        // but if there are only 11 lines,
                        // we show the last line instead of a line saying that there is 1 more line.
                        // (As a bonus - "x more lines" is always plural)
                        var newText = changingText.Replace(changingText.TextSpan, 
                            """
                            New text content (Line 1)
                            New text content (Line 2)
                            New text content (Line 3)
                            New text content (Line 4)
                            New text content (Line 5)
                            New text content (Line 6)
                            New text content (Line 7)
                            New text content (Line 8)
                            New text content (Line 9)
                            New text content (Line 10)
                            New text content (Line 11)
                            """);
                        driver = driver.ReplaceAdditionalText(changingText, newText);
                    }

                    return (driver, compilation);
                },
                InputSource);

        // Assert the output
        diagnostics.ShouldBeEmpty();
        output1.LastOrDefault().ShouldBe(ExpectedOutput1);
        output2.LastOrDefault().ShouldBe(
            ExpectedOutput1
                .Replace("/// Example text content", "/// New text content")
                .Replace("/// ... 2 more lines", "/// New text content (Line 11)")
            );
    }

    [Fact]
    public void ModifiedTextAfterTenthLine_PipelineEntirelyCached()
    {
        // run the generator, passing in the inputs and the tracking names
        var (diagnostics, output1, output2)
            = TestHelper.GetGeneratedOutput<Generator>(
                TestHelper.NoModification,
                _additionalTexts,
                [
                    nameof(GeneratorStage.ForAttributeWithMetadataName),
                    nameof(GeneratorStage.AnalyzerConfigOptionsProviderSelect),
                    nameof(TrackingNames.AttributesAndOptionsCombined),
                    nameof(TrackingNames.AttributeGlobInfoSelected),
                    nameof(TrackingNames.AttributeGlobsSelected),
                    nameof(TrackingNames.MatchingResourceAndAttributeSelected),
                    nameof(TrackingNames.ResourcesGroupedByAttributeContext),
                    nameof(TrackingNames.GenerationInputPrepared)
                ],
                (driver, compilation) =>
                {
                    if (_additionalTexts[0] is InMemoryAdditionalText changingText)
                    {
                        var newText = changingText.Replace(changingText.TextSpan, 
                            """
                            Example text content (Line 1)
                            Example text content (Line 2)
                            Example text content (Line 3)
                            Example text content (Line 4)
                            Example text content (Line 5)
                            Example text content (Line 6)
                            Example text content (Line 7)
                            Example text content (Line 8)
                            Example text content (Line 9)
                            Example text content (Line 10)
                            New text content (Line 11)
                            New text content (Line 12)
                            """);
                        driver = driver.ReplaceAdditionalText(changingText, newText);
                    }

                    return (driver, compilation);
                },
                InputSource);

        // Assert the output
        diagnostics.ShouldBeEmpty();
        output1.LastOrDefault().ShouldBe(ExpectedOutput1);
        output2.LastOrDefault().ShouldBe(ExpectedOutput1);
    }

    [Fact]
    public void DesignTimeBuild_DoesNotReadFiles()
    {
        // run the generator, passing in the inputs and the tracking names
        var (diagnostics, output1, output2)
            = TestHelper.GetGeneratedOutput<Generator>(
                (driver, compilation) =>
                {
                    var newOptions = new TestConfigOptionsProvider(true);
                    driver = driver.WithUpdatedAnalyzerConfigOptions(newOptions);
                    return (driver, compilation);
                },
                _additionalTexts,
                [], // Not interested in changes to tracking names for this test
                TestHelper.NoModification,
                InputSource);

        // Assert the output
        diagnostics.ShouldBeEmpty();
        var expected = """
                       //------------------------------------------------------------------------------
                       // <auto-generated>
                       //     This code was generated by the Datacute.EmbeddedResourcePropertyGenerator.
                       // </auto-generated>
                       //------------------------------------------------------------------------------

                       #nullable enable

                       namespace EmbeddedResourcePropertyGenerator.Tests;
                       
                       public static partial class Queries
                       {
                           private static class EmbeddedResource
                           {
                           }
                           static partial void ReadEmbeddedResourceValue(ref string? backingField, string resourceName, string propertyName);
                           static partial void AlterEmbeddedResourceReturnValue(ref string value, string resourceName, string propertyName);
                           public static string Example => "Design Time";
                       }

                       """;
        output1.LastOrDefault().ShouldBe(expected);
        output2.LastOrDefault().ShouldBe(expected);
    }
}