//HintName: _EmbeddedResourceReader.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Datacute.EmbeddedResourcePropertyGenerator.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Datacute.EmbeddedResourcePropertyGenerator;

public static class EmbeddedResourceReader
{
    public static string Read(Type containingType, string resourceName)
    {
        var assembly = containingType.Assembly;
        using var stream = assembly.GetManifestResourceStream(resourceName)!;
        using var streamReader = new global::System.IO.StreamReader(stream, global::System.Text.Encoding.UTF8);
        var resourceText = streamReader.ReadToEnd();
        return resourceText;
    }
}