name: CI

on:
  push:
    branches:
    - main
    - alpha
  pull_request:
    branches:
    - main
  workflow_dispatch:
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'EmbeddedResourceProperty.sln'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore $env:SOLUTION

    - name: Build
      run: dotnet build $env:SOLUTION --configuration $env:BUILD_CONFIG --no-restore

    - name: Run tests
      run: dotnet test --configuration $env:BUILD_CONFIG --no-restore --no-build --verbosity normal
